name: r_scrapingrank
description: A new Flet application.

environment:
  sdk: ">=2.17.0 <3.0.0"  # Flutterバージョンに対応するDart SDKバージョン

dependencies:
  flutter:
    sdk: flutter
  flet: ^0.22.1  # 最新バージョンを指定

flutter:
  assets:
    - assets/icons/app_icon.png  # アイコンファイルのパス
