name: r_scrapingrank
description: A new Flet application.

environment:
  sdk: ">=3.2.0 <4.0.0"  # Dart SDKバージョンを3.2.0以降に変更

dependencies:
  flutter:
    sdk: flutter
  flet: ^0.22.1  # 最新バージョンを指定

flutter:
  assets:
    - assets/icons/app_icon.png  # アイコンファイルのパス
    